---
title: "Algorithm2"
author: "Wael"
date: "22/03/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(stats)
library(Matrix)
library(mc2d)
```


```{r}

msqrt <- function(M){
  #Inputs
  # M: a (squar and pos. def.) matrix
  E <- eigen(M)
  d <- (E$values)^(-1/2)
  P <- E$vectors
  
  return(P %*% diag(d) %*% t(P))
  
}

projection_0m <- function(X){
  #Inputs:
  # X: a matrix
  Y <- msqrt(t(X) %*% X)
  return( X %*% Y)
  
}
projection_rankm <- function(A, k){ #LOW-RANK projection of matrices
  #Inputs: 
  # A: array (or matrix) of rank n > k
  # k: rank required
  n <- dim(A)[1]
  S <- svd(A,k,k)
  U <- S$u
  sigma <- head(S$d, -(n-k))
  D <- diag(sigma)
  V <- S$v
  return(U %*% D %*% t(V))
  
}

projection_rankt <- function(A, K){#Low-rank projection of tensors
  #Inputs:
  # A: tensor, where A[i,,] is a matrix of rank ni > ki
  # k: vectors of rank for each matrices A[i,,]
  d <- dim(A)
  Y <- array(0,d)
  for(i in 1:d[1]){
    Y[i,,] <- projection_rankm(A[i,,], K[i])
  }
  return(Y)
  
}


```

```{r}
prod_1 <- function(X, A){
  
  d <- dim(X)
  m <- dim(A)[1]
  Y <- array(1,c(m, d[2], d[3]))
  X_t <- matrix(1,d[1], d[2]*d[3])
  for(i in 1:d[1]){
    X_t[i,]<-c(X[i,,])
  }
  Y_t <- A %*% X_t
  
  for(i in 1:m){
    Y[i,,] <- array(c(Y_t[i,]),d[-1])
  }
  return(Y)

}

prod_2_3 <- function(A, Q){
  d1 <- dim(A)
  d2 <- dim(Q)
  Y <- matrix(0,d1[1], d2[1])
  for(i in 1:d1[1]){
    for(j in 1:d2[1]){
      Y[i,j] <- sum(diag(A[i,,] %*% t(Q[j,,])))
    }
  }
  return(Y)
  
  
}
```

```{r}
init_algo3 <- function(A,m){
  #Inputs:
  # A: adjacency tensor of dim l x n x n
  # m: number of class of layer
  d <- dim(A)
  A_t <- matrix(0,d[1], d[2]*d[3])
  for(i in 1:d[1]){
    A_t[i,]<-c(A[i,,])
  }
  S <- svd(A_t, nu = m)
  W_0 <- S$u
  me <- kmeans(W_0, m, iter.max = 100)
  cent <- me$cluster
  L <- 1:m
  
  Z <- array(0, c(d[1], m))
  for(i in 1:d[1]){
    Z[i,] <- c(L== cent[i])
  }
  
  return(projection_0m(Z))
}
```

```{r}
Algo_3 <- function(A, K, iter_max = 100){
  #Inputs:
  # A: adjacency tensor of dimension Lxnxn
  # K: vector of length M (=number of class of layers) and K_i = number of communities in class i
  M <- length(K)
  L <- dim(A)[1]
  n <- dim(A)[2]
  
  #Initialization:
  W_old <- t(init_algo3(A, M))
  #W_old <- diag(1, M, L)
  #iteration
  i <- 0
  while(i < iter_max){
    i <- i + 1
    #print(A[1,,]
    Q_1 <- prod_1(A, W_old)
    Q_new <- projection_rankt( Q_1, K)
    #print(Q_new[1,,])
    Z <- prod_2_3(A, Q_new)
    #print(t(Z) %*% Z)
    W_old <- t(projection_0m( prod_2_3(A, Q_new)))
  }
  
  
  return(list(Q_new, W_old))
}
```


```{r}
network <- simul_final(50, c(2, 2), c(3,4),2)
Ad <- network[[1]]



r <- Algo_3(network[[1]], c(3, 2))

W_0 <- r[[2]]


```


```{r}
layer_comm <- function(W, m){
  l <- dim(W)[2]
  g <- kmeans(t(W), m)$cluster
  L <- 1:m
  Z <- array(0, c(l, m))
  for(i in 1:l){
    Z[i,] <- c(L== g[i])
  }
  
  return(Z)
}
nodes_comm <- function(Q, K){
  m <- length(K)
  n <- dim(Q)[2]
  g <- list()
  Z <- list()
  for(i in 1:m){
    Qi <- Q[i,,]
    Ui <- eigen(Qi)$vectors
    Uit <- matrix(0,n, K[i] )
    for(j in 1:K[i]){
      Uit[,j] <- Ui[,j]
      
    }
    g[[i]] <- kmeans(Uit, K[i])$cluster
    Zi <- array(0, c(n, m))
    L <- 1:m
    for(j in 1:n){
      Zi[j,] <- c(L== g[[i]][j])
    }
    Z[[i]] <- Zi
  }
  return(list(g, Z))
}


```

```{r}
y <- layer_comm(r[[2]], 2)
x <- nodes_comm(r[[1]], c(2,2))
```












